
name: Tapsnap
settings:
  DEVELOPMENT_TEAM: K78G42H4U2
options:
  createIntermediateGroups: true
  bundleIdPrefix: app.beta.tapsnap
  transitivelyLinkDependencies: true
packages:
  Publish:
    url: https://github.com/johnsundell/publish
    from: 0.1.0
  SensorVisualizerKit:
    url: https://github.com/joeblau/sensor-visualizer-kit
    from: 0.2.0
targets:
  Tapsnap:
    type: application
    platform: iOS
    scheme:
      testTargets:
        - TapsnapTests
      gatherCoverageData: true
    sources:
      - Tapsnap
    dependencies:
      - package: SensorVisualizerKit
  TapsnapTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - TapsnapTests
    dependencies:
      - target: Tapsnap
  Web:
    type: tool
    platform: macOS
    sources:
      - Website/Sources/
    dependencies:
      - package: Publish