
name: Tapsnap
settings:
  DEVELOPMENT_TEAM: 5WSA243UP9
options:
  createIntermediateGroups: true
  bundleIdPrefix: app.tapsnap
  transitivelyLinkDependencies: true
targets:
  Tapsnap:
    type: application
    platform: iOS
    scheme:
      testTargets:
        - TapsnapTests
      gatherCoverageData: true
    sources:
      - Tapsnap
    settings:
      TARGETED_DEVICE_FAMILY: 1
      CODE_SIGN_ENTITLEMENTS: Tapsnap/Tapsnap.entitlements
    dependencies:
      - package: SensorVisualizerKit
  TapsnapTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - TapsnapTests
    dependencies:
      - target: Tapsnap